# Generated by Django 3.2.6 on 2021-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_create_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_text',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
